# Generated by Django 5.1.1 on 2024-10-31 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_code_appliance_brand_remove_appliance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
