# Generated by Django 5.1.1 on 2024-11-04 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appliance_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='amperage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='appliance_model',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='app.appliance'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='average_temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='average_temperature_freezer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='electric_power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='voltage',
            field=models.FloatField(default=0.0),
        ),
    ]
