# Generated by Django 5.1.1 on 2024-11-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_applianceoperator_delete_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applianceoperator',
            name='limit_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='applianceoperator',
            name='observations',
            field=models.TextField(default=None, null=True),
        ),
    ]
